import fs from "node:fs";

function n(s) {
  return String(s)
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/['’]/g, "")
    .replace(/&/g, "e")
    .replace(/[^a-z0-9]+/g, "");
}

const PARES = [
  ["CB-9 Explosive Crossbow", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/CB-9-EXPLODING-CROSSBOW.png"],
  ["R-36 Eruptor", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/R36ERUPTOR.png"],
  ["SG-8 Punisher Plasma", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/SG8PPUNISHERPLASMA.png"],
  ["PLAS-101 Purifier", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/PLAS-101-PURIFIER.png"],
  ["R-72 Censor", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/01/R-72-Censor-HD2-Primary.png"],
  ["R-63 Diligence", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/R63DILIGENCE.png"],
  ["PLAS-1 Scorcher", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/PLAS-1-SCORCHER.png"],
  ["R-2 Amendment", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/05/R2-Amendment.png"],
  ["LAS-13 Trident", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/01/LAS-16-Trident.png"],
  ["R-63CS Diligence Counter Sniper", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/R63CSDILIGENCECOUNTERSNIPER-1.png"],
  ["VG-70 Variable", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/07/VG-70-Variable.png"],
  ["AR-2 Coyote", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/HD2Primary-AR2Coyote.png"],
  ["DBS-2 Double Freedom", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/11/HD2-DoubleFreedom.png"],
  ["LAS-17 Double-Edge Sickle", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/12/LAS-17-Double-Edge-Sickle.png"],
  ["PLAS-39 Accelerator Rifle", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/12/PLAS-39-Accelerator-Rifle.png"],
  ["JAR-5 Dominator", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/JAR5DOMINATOR.png"],
  ["LAS-5 Scythe", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/LAS5SCYTHE.png"],
  ["SG-97 Sweeper", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/03/HD2-Primary-Sweeper.png"],
  ["R-4 Hyena", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/07/2560px-R-4_Hyena_Primary_Render.webp"],
  ["AR-59 Suppressor", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/01/AR-59-Suppressor-HD2-Primary.png"],
  ["BR-14 Adjudicator", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/BR14ADJUDICATOR.png"],
  ["AR-23P Liberator Penetrator", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/AR23PPENETRATOR.png"],
  ["SMG-32 Reprimand", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/10/SMG-32-Reprimand.png"],
  ["AR-61 Tenderizer", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/AR61TENDERIZER.png"],
  ["AR/GL-21 One-Two", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/11/HD2-OneTwo.png"],
  ["AR-23 Liberator", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/AR23LIBERATOR.png"],
  ["AR-23A Liberator Carbine", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/06/AR23ALIBERATORCARBINE.png"],
  ["LAS-16 Sickle", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/LAS16SICKLE.png"],
  ["SG-20 Halt", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/10/SG-20-Halt.png"],
  ["MP-98 Knight", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/MP98KNIGHT.png"],
  ["AR-32 Pacifier", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/07/AR32-PACIFIER.png"],
  ["SMG/FLAM-34 Stoker", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/03/HD2-Primary-SMG-FLAM-34-Stoker.png"],
  ["SMG-203 Gallant", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/04/HD2-Primary-SMG203-Gallant.png"],
  ["SMG-37 Defender", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/SMG37DEFENDER.png"],
  ["SG-225IE Breaker Incendiary", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/SG225IEBREAKERINCENDIARY.png"],
  ["SG-225 Breaker", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/SG225BREAKER.png"],
  ["SG-451 Cookout", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/07/SG451COOKOUT.png"],
  ["SG-8 Punisher", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/SG8PUNISHER.png"],
  ["SG-225SP Breaker SPRAY & PRAY", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/SG225SPSPRAYPRAY.png"],
  ["R-6 Deadeye", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/02/R6-Deadeye.png"],
  ["FLAM-66 Torcher", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/07/FLAM-66TORCHER.png"],
  ["MA5C Assault Rifle", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/08/MA5C-Assault-Rifle.png"],
  ["M7S SMG", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/08/M7S-SMG.png"],
  ["StA-52 Assault Rifle", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/12/StA-52-Assault-Rifle.png"],
  ["StA-11 SMG", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/12/StA-11-SMG.png"],
  ["AR-23C Liberator Concussive", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/AR23CCONCUSSIVE.png"],
  ["M90A Shotgun", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/08/M90A-Shotgun.png"],
  ["SMG-72 Pummeler", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/SMG72PUMMELER.png"],
  ["SG-8S Slugger", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/SG8SSLUGGER.png"],
  ["ARC-12 Blitzer", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/ARC-12-BLITZER.png"],
  ["R-2124 Constitution", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/11/R-2124-Constitution.png"],
  ["LAS-58 Talon", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/10/LAS-58-Talon.png"],
  ["PLAS-15 Loyalist", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/12/PLAS-15-Loyalist.png"],
  ["GP-31 Grenade Pistol", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/GP-31-GRENADE-PISTOL.png"],
  ["P-72 Crisper", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/06/P-72-Crisper.png"],
  ["P-35 Re-Educator", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/01/P-35-Re-Educator-HD2-Secondary.png"],
  ["P-92 Warrant", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/10/P-92-Warrant.png"],
  ["P-113 Verdict", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/P-113-VERDICT.png"],
  ["P-69 Veto", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/03/HD2-Secondary-P-69-Veto.png"],
  ["P-4 Senator", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/P4SENATOR.png"],
  ["GP-20 Ultimatum", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/HD2Secondary-Ultimatum.png"],
  ["P-19 Redeemer", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/P19REDEEMER-1.png"],
  ["P-11 Stim Pistol", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/06/P-11-Stim-Pistol.png"],
  ["M6C-SOCOM", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/10/M6C-Socom.png"],
  ["CQC-2 Saber", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/05/CQC-2-Saber.png"],
  ["CQC-5 Combat Hatchet", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/10/CQC-5-Combat-Hatchet.png"],
  ["CQC-42 Machete", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/HD2Melee-Machete.png"],
  ["LAS-7 Dagger", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/LAS-7-DAGGER.png"],
  ["P-33 Missile Pistol", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/04/HD2-Secondart-P33-MISSILEPISTOL.png"],
  ["SG-22 Bushwhacker", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/12/SG-22-BUSHWHACKER.png"],
  ["P-2 Peacemaker", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/P2PEACEKEEPER.png"],
  ["CQC-19 Stun Lance", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/12/CQC-19-Stun-Lance.png"],
  ["CQC-30 Stun Baton", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/12/CQC-30-Stun-Baton.png"],
  ["CQC-73 Entrenchment Tool", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/03/HD2-Secondary-CQC-72-Entrenchment-Tool.png"],
  ["RL-77 Airburst Rocket Launcher", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Airburst-Rocket-Launcher.png"],
  ["M-105 Stalwart", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Stalwart.png"],
  ["FLAM-40 Flamethrower", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Flamethrower.png"],
  ["AC-8 Autocannon", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Autocannon.png"],
  ["StA-X3 W.A.S.P. Launcher", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-StA-X3-W.A.S.P.-Launcher.png"],
  ["B/FLAM-80 Cremator", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/03/B-FLAM-80_Cremator_Stratagem_Icon.png"],
  ["MGX-42 Bullet Storm", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/04/HD2-BulletStorm-Stratagem.png"],
  ["S-11 Speargun", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-SpeargunV2.png"],
  ["GL-21 Grenade Launcher", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Grenade-Launcher.png"],
  ["MG-43 Machine Gun", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Machine-Gun.png"],
  ["EAT-700 Expendable Napalm", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-EAT-700-Expendable-NapalmV2.png"],
  ["B/MD C4 Pack", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/01/BMD-C4-Pack-HD2-Support-Weapon.png"],
  ["EAT-411 Leveller", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/02/EAT-411.png"],
  ["MS-11 Solo Silo", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Solo-SiloV2.png"],
  ["CQC-20 Breaching Hammer", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/02/CQC-20.png"],
  ["ARC-3 Arc Thrower", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Arc-Thrower.png"],
  ["GL-52 De-Escalator", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-GL-52-De-Escalator.png"],
  ["M-1000 Maxigun", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/Maxigun.png"],
  ["GL-28 Belt-Fed Grenade Launcher", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/02/GL-28.png"],
  ["MLS-4X Commando", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Commando.png"],
  ["PLAS-45 Epoch", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Epoch.png"],
  ["MG-206 Heavy Machine Gun", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Heavy-Machine-Gun.png"],
  ["LAS-98 Laser Cannon", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Laser-Cannon.png"],
  ["GR-8 Recoilless Rifle", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Recoilless-Rifle.png"],
  ["APW-1 Anti-Materiel Rifle", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Anti-Materiel-Rifle.png"],
  ["FAF-14 Spear", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Spear.png"],
  ["RS-422 Railgun", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Railgun.png"],
  ["EAT-17 Expendable Anti-Tank", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Expendable-Anti-Tank.png"],
  ["LAS-99 Quasar Cannon", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Quasar-Cannon.png"],
  ["TX-41 Sterilizer", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Sterilizer.png"],
  ["CQC-9 Defoliation Tool", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/Defoliation-Tool.png"],
  ["CQC-1 One True Flag", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-One-True-Flag.png"],
  ["G-123 Thermite", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/ThermiteGrenade.png"],
  ["G-142 Pyrotech", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/10/G-142-Pyrotech.png"],
  ["TED-63 Dynamite", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/10/TED63-Dynamite.png"],
  ["G-23 Stun", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/StunGrenade.png"],
  ["G/SH-39 Shield", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/03/GSH-39-Shield-Grenade-HD2.png"],
  ["G-4 Gas", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/10/G-4-Gas.png"],
  ["TM-1 Lure Mine", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/01/TM-1-Lure-Mine-HD2-Throwable.png"],
  ["G-12 High Explosive", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/HighExplosiveGrenade.png"],
  ["G-16 Impact", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/ImpactGrenade.png"],
  ["G-7 Pineapple", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/10/G7-Pineapple.png"],
  ["G-50 Seeker", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/10/G-50-Seeker.png"],
  ["G-48 Giga Grenade", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/03/HD2-Throwable-G-48-Giga-Grenade.png"],
  ["G-13 Incendiary Impact", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/IncendiaryImpactGrenade.png"],
  ["G-10 Incendiary", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/IncendiaryGrenade.png"],
  ["G-6 Frag", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/FragGrenade.png"],
  ["G-89 Smokecreen", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/11/G-89-Smokescreen-HD2-Throwable-1.png"],
  ["G-3 Smoke", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/SmokeGrenade.png"],
  ["G-31 Arc", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/11/G-31-Arc.png"],
  ["G-109 Urchin", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/11/G-109-Urchin.png"],
  ["K-2 Throwing Knife", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/10/K-2-Throwing-Knife.png"],
  ["AX/FLAM-75 Hot Dog", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/01/Guard-Dog-Hot-Dog-v4.png"],
  ["LIFT-182 Warp Pack", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Warp-Pack.png"],
  ["B-1 Supply Pack", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Supply-Pack.png"],
  ["B-100 Portable Hellbomb", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Hellbomb-Portable.png"],
  ["AX/AR-23 Guard Dog", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Guard-Dog.png"],
  ["LIFT-850 Jump Pack", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Jump-Pack.png"],
  ["SH-32 Shield Generator Pack", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Shield-Generator-Pack.png"],
  ["AX/LAS-5 Rover", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Guard-Dog-Rover.png"],
  ["LIFT-860 Hover Pack", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Hover-Pack.png"],
  ["AX/ARC-3 K-9", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/01/Guard-Dog-K9.png"],
  ["AX/TX-13 Dog Breath", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Guard-Dog-Breath.png"],
  ["SH-20 Ballistic Shield Backpack", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Ballistic-Shield-Backpack.png"],
  ["SH-51 Directional Shield", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Directional-Shield.png"],
  ["Eagle Strafing Run", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Eagle-Strafing-Run.png"],
  ["Eagle Napalm Airstrike", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Eagle-Napalm-Airstrike.png"],
  ["Eagle Airstrike", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Eagle-Airstrike.png"],
  ["Eagle Cluster Bomb", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Eagle-Cluster-Bomb.png"],
  ["Eagle 500kg Bomb", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Eagle-500KG-Bomb.png"],
  ["Eagle Smoke Strike", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Eagle-Smoke-Strike.png"],
  ["Eagle 110mm Rocket Pods", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Eagle-110MM-Rocket-Pods.png"],
  ["E/AT-12 Anti-Tank Emplacement", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Anti-Tank-Emplacement.png"],
  ["A/MG-43 Machine Gun Sentry", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Machine-Gun-Sentry.png"],
  ["A/ARC-3 Tesla Tower", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Tesla-Tower.png"],
  ["A/G-16 Gatling Sentry", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Gatling-Sentry.png"],
  ["A/AC-8 Autocannon Sentry", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Autocannon-Sentry.png"],
  ["E/MG-101 HMG Emplacement", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-HMG-Emplacement.png"],
  ["A/FLAM-40 Flame Sentry", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Flame-Sentry.png"],
  ["A/MLS-4X Rocket Sentry", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Rocket-Sentry.png"],
  ["MD-I4 Incendiary Mines", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Incendiary-Mines.png"],
  ["MD-8 Gas Mines", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Gas-Mine.png"],
  ["A/LAS-98 Laser Sentry", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Laser-Sentry.png"],
  ["A/M-23 EMS Mortar Sentry", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-EMS-Mortar-Sentry.png"],
  ["MD-6 Anti-Personnel Minefield", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Anti-Personnel-Minefield.png"],
  ["E/GL-21 Grenadier Battlement", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Grenadier-Battlement.png"],
  ["A/GM-17 Gas Mortar Sentry", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/03/HD2-Gas-Mortar-Sentry.png"],
  ["FX-12 Shield Generator Relay", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Shield-Generator-Relay.png"],
  ["A/M-12 Mortar Sentry", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Mortar-Sentry.png"],
  ["MD-17 Anti-Tank Mines", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Anti-Tank-Mines.png"],
  ["Hellpod Space Optimization", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/hellpod-optimisation.png"],
  ["Experimental Infusion", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/07/130px-Experimental_Infusion_Booster_Icon.webp"],
  ["Stamina Enhancement", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/stamina-enhancement.png"],
  ["Vitality Enhancement", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/vitality-enhancement.png"],
  ["Increased Reinforcement Budget", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/increased-reinforcement-budget.png"],
  ["Armed Resupply Pods", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/03/HD2-Booster-ArmedResupplyPods.png"],
  ["Sample Extricator", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/07/HD2_Booster_SampleExtricator.png"],
  ["Sample Scanner", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/07/Sample_Scanner_Booster_Icon.png"],
  ["Muscle Enhancement", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/muscle-enhancement.png"],
  ["Flexible Reinforcement Budget", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/flexible-reinforcement-budget.png"],
  ["Localization Confusion", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/localisation-confusion.png"],
  ["Dead Sprint", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/03/HD2-Booster-DeadSprint.png"],
  ["Expert Extraction Pilot", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/expert-extraction-pilot.png"],
  ["Firebomb Hellpods", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/06/Firebomb_Hellpods_Booster_Icon.png"],
  ["UAV Recon Booster", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/05/uav-recon-booster.png"],
  ["Motivational Shocks", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/06/motivational-shocks-v2.png"],
  ["Stun Pods", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/03/HD2-Booster-StunPods.png"],
  ["Concealed Insertion", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/03/HD2-Booster-ConcealedInsertion.png"],
  ["Med-Kit", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/07/armor-passive-medkit.png"],
  ["True Grit", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/08/HD2-ArmorPassive-TrueGrit.jpg"],
  ["Reduced Signature", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/12/ReducedSignatureArmorPassiveHD2.jpg"],
  ["Siege-Ready", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/07/Siege-Ready_Armor_Passive_Icon.webp"],
  ["Engineering Kit", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/07/armor-passive-engineeringkit.png"],
  ["Oxygenator", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/04/HD2-ArmorPassive-Oxygenator.jpg"],
  ["Concussive Padding, Reinforced", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/03/HD2-ArmorPassive-ConcussivePadding.jpg"],
  ["Desert Stormer", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/12/HD2DesertStormerArmorPassive.jpg"],
  ["Adreno-Defibrillator", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/12/boosterIcon_AdrenoDefib.jpg"],
  ["Ballistic Padding", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/12/boosterIcon_BallisticPadding.jpg"],
  ["Acclimated", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/12/boosterIcon_Acclimated.jpg"],
  ["Unflinching", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/07/Unflinching_Armor_Passive_Icon.webp"],
  ["Peak Physique", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/07/armor-passive-peakphysique.png"],
  ["Electrical Conduit", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/07/armor-passive-medkit.png"],
  ["Democracy Protects", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/12/boosterIcon_DemocracyProtects.jpg"],
  ["Concussive Padding, Hazmat", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/03/HD2-ArmorPassive-ConcussivePadding.jpg"],
  ["Concussive Padding, Grenadier", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/03/HD2-ArmorPassive-ConcussivePadding.jpg"],
  ["Rock Solid", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/12/HD2RockSolidArmorPassive.jpg"],
  ["Reinforced Epaulettes", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/12/boosterIcon_ReinforcedEpaulettes.jpg"],
  ["Gunslinger", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/12/boosterIcon_Gunslinger.jpg"],
  ["Fortified", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/07/armor-passive-fortified.png"],
  ["Scout", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/07/armor-passive-scout.png"],
  ["Extra Padding", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/07/armor-passive-extrapadding.png"],
  ["Supplementary Adrenaline", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/12/SupplementaryAdrenalineArmorPassiveHD2.jpg"],
  ["Kinetic Displacement Mitigation", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/08/HD2-ArmorPassive-KineticDisplacementMitigation.jpg"],
  ["Feet First", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/12/HD2FeetFirstArmorPassive.jpg"],
  ["Integrated Explosives", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/12/boosterIcon_IntegratedExplosives.jpg"],
  ["Advanced Filtration", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/12/boosterIcon_AdvancedFiltration.jpg"],
  ["Inflammable", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/06/Inflammable_Armor_Passive_Icon.png"],
  ["Servo-Assisted", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2024/07/armor-passive-servoassisted.png"],
  ["Democratic Detonation", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/07/wbicon_DemocraticDetonation.jpg"],
  ["Dust Devils", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/wbicon_DustDevils.jpg"],
  ["Control Group", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/07/wbicon_ControlGroup.jpg"],
  ["Servants of Freedom", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/07/wbicon_ServantsOfFreedom.jpg"],
  ["Redacted Regiment", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/wbicon_RedactedRegiment.jpg"],
  ["Polar Patriots", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/07/wbicon_PolarPatriots.jpg"],
  ["Siege Breakers", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/wbicon_SiegeBreakers.jpg"],
  ["Exo Experts", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/04/wbicon_ExoExperts.jpg"],
  ["Urban Legends", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/07/wbicon_UrbanLegends.jpg"],
  ["Entrenched Division", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/03/wbicon_Entrenched.jpg"],
  ["Borderline Justice", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/07/wbicon_BorderlineJustice.jpg"],
  ["Freedom’s Flame", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/07/wbicon_FreedomsFlame.jpg"],
  ["Chemical Agents", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/07/wbicon_ChemicalAgents.jpg"],
  ["Cutting Edge", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/07/wbicon_CuttingEdge.jpg"],
  ["Steeled Veterans", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/07/wbicon_SteeledVeterans.jpg"],
  ["Viper Commandos", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/07/wbicon_ViperCommandos.jpg"],
  ["Truth Enforcers", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/07/wbicon_TruthEnforcers.jpg"],
  ["Python Commandos", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/12/wbicon_PythonCommandos.jpg"],
  ["Force of Law", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/07/wbicon_ForceOfLaw.jpg"],
  ["Masters of Ceremony", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/07/wbicon_MastersOfCeremony.jpg"],
  ["Halo: ODST", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/07/wbicon_ODST.jpg"],
  ["Righteous Revenants", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/wbicon_Killzone.jpg"],
  ["Orbital Laser", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Orbital-Laser.png"],
  ["Orbital Precision Strike", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Orbital-Precision-Strike.png"],
  ["Orbital Gas Strike", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Orbital-Gas-Strike.png"],
  ["Orbital Napalm Barrage", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Orbital-Napalm-Barrage.png"],
  ["Orbital Gatling Barrage", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Orbital-Gatling-Barrage.png"],
  ["Orbital 120mm HE Barrage", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Orbital-120MM-HE-Barrage.png"],
  ["Orbital Airburst Strike", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Orbital-Airburst-Strike.png"],
  ["Orbital Walking Barrage", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Orbital-Walking-Barrage.png"],
  ["Orbital EMS Strike", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Orbital-EMS-Strike.png"],
  ["Orbital 380mm HE Barrage", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Orbital-380MM-HE-Barrage.png"],
  ["Orbital Smoke Strike", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Orbital-Smoke-Strike.png"],
  ["Orbital Railcannon Strike", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2025/09/hd2-stratagem-Orbital-Railcannon-Strike.png"],
  ["M-102 Fast Recon Vehicle", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/04/HD2-FRV-Stratagem.png"],
  ["TD-220 Bastion MK XVI", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/04/HD2-Bastion-Tank-Stratagem.png"],
  ["M-104 Incinerator FRV", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/07/Incinerator-FRV.png"],
  ["M-103 Supply FRV", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/07/SupplyFRV.png"],
  ["EXO-49 Emancipator Exosuit", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/04/HD2-Emancipator-Mech-Stratagem.png"],
  ["EXO-55 Breakthrough Exosuit", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/04/HD2-Breakthrough-Mech-Stratagem.png"],
  ["EXO-51 Lumberer Exosuit", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/04/HD2-Lumberer-Mech-Stratagem.png"],
  ["EXO-45 Patriot Exosuit", "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/04/HD2-Patriot-Mech-Stratagem.png"],
];

const mapa = {};
for (const [alt, src] of PARES) {
  mapa[n(alt)] = src;
}

const saida = `window.IMAGENS = ${JSON.stringify(mapa, null, 2)};

window.IMAGENS_FACCAO = {
  automatons: "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/03/AutomatonIco.png",
  terminids: "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/03/TerminidIco.png",
  illuminate: "https://s3.us-east-2.amazonaws.com/wp.uggcms/wp-content/uploads/2026/03/IlluminateIco.png"
};
`;

fs.writeFileSync(new URL("../assets/data/imagens.js", import.meta.url), saida);
console.log("icones", Object.keys(mapa).length);
